server:
  port: 8010
spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&parseTime=True&loc=Local&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  devtools:
    livereload:
      port: 35730
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.main.Entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka